name: Copy Docs Pull Request

on:
  schedule:
    - cron: '0,15,30,45 * * * *'  # Schedule the workflow to run once a day
  workflow_dispatch:

jobs:
  copy_docs_and_submit_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "josh-wong"
          git config --global user.email "joshuarwong@gmail.com"

      - name: Clone and Copy Docs from sandbox-copy-docs-source-1
        run: |
          git clone https://github.com/josh-wong/sandbox-copy-docs-source-1.git sandbox-copy-docs-source-1
          cp -r sandbox-copy-docs-source-1/docs sandbox-copy-docs-destination/docs

      - name: Clone and Copy Docs from sandbox-copy-docs-source-2
        run: |
          git clone https://github.com/josh-wong/sandbox-copy-docs-source-2.git sandbox-copy-docs-source-2
          cp -r sandbox-copy-docs-source-2/docs sandbox-copy-docs-destination/docs

      # Add more steps for each repository you want to copy from

      - name: Commit and Push Changes
        run: |
          cd sandbox-copy-docs-destination
          git add .
          git commit -m "Copy docs from multiple repositories"
          git push origin main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.COPY_DOCS_TOKEN }}
          title: Copy docs from multiple repositories
          body: |
            This pull request copies the contents of the "docs" folder from source repositories that have updated contents in their `docs` folders.

          base: main
          draft: false