name: Copy Docs and Submit Pull Request

on:
  schedule:
    - cron: '0,15,30,45 * * * *'  # Schedule the workflow to run every 30 minutes

jobs:
  copy_docs_and_submit_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Destination Repository
        uses: actions/checkout@v3
        with:
          repository: josh-wong/sandbox-copy-docs-destination  # Replace with the destination repository details

      - name: Copy Docs from sandbox-copy-docs-source-1
        uses: actions/checkout@v3
        with:
          repository: josh-wong/sandbox-copy-docs-source-1  # Replace with the first source repository details
          ref: main  # Replace with the desired branch name

      - name: Copy Docs from sandbox-copy-docs-source-2
        uses: actions/checkout@v3
        with:
          repository: josh-wong/sandbox-copy-docs-source-2  # Replace with the second source repository details
          ref: main  # Replace with the desired branch name

      # Add more steps for each repository you want to copy from

      - name: Check for Changes
        id: check_changes
        run: |
          git diff --quiet HEAD -- docs
          echo ::set-output name=has_changes::!$?

      - name: Move Docs to Destination
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          mkdir -p docs/new
          cp -r docs docs/new

      - name: Configure Git
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "joshuarwong@gmail.com"
          git config --local user.name "josh-wong"

      - name: Create Branch
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git checkout -b add-updated-docs
          git add .
          git commit -m "Copy docs from source repository"

      - name: Push Branch
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.COPY_DOCS_TOKEN }}
          branch: add-updated-docs

      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.COPY_DOCS_TOKEN }}
          branch: add-updated-docs
          title: Copy docs from source repository
          body: |
            This pull request copies the contents of the "docs" folder
            from multiple repositories.
          base: main
          draft: false
