name: Copy Docs and Submit Pull Request

on:
  push:
    branches:
      - main
  schedule:
    # ATTENTION: To reduce GitHub Action usage, set cron to '0 0 1 * *' (at 12:00 AM on the 1st of the month) when not inactive
    - cron: '0,15,30,45 * * * *'  # Schedule the workflow to run every XX:00, XX:15, XX:30, and XX:45 ('0,15,30,45 * * * *')

jobs:
  copy_docs_and_submit_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Set up Git credentials
        run: |
          git config --global user.email "joshuarwong@gmail.com"
          git config --global user.name "josh-wong"

      - name: Clone other repositories
        run: |
          git clone --depth 1 --branch main https://github.com/josh-wong/sandbox-copy-docs-source-1 sandbox-copy-docs-source-1
          git clone --depth 1 --branch main https://github.com/josh-wong/sandbox-copy-docs-source-2 sandbox-copy-docs-source-2

      - name: Check for Changes
        id: check_changes
        run: |
          diff=$(git diff sandbox-copy-docs-source-1/docs sandbox-copy-docs-source-2/docs)
          if [ -n "$diff" ]; then
            echo "::set-output name=has_changes::true"
          else
            echo "::set-output name=has_changes::false"
          fi

      - name: Move Docs to Main Repository
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          cp -r sandbox-copy-docs-source-1/docs sandbox-copy-docs-destination/docs
          cp -r sandbox-copy-docs-source-2/docs sandbox-copy-docs-destination/docs

      - name: Commit Changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          cd sandbox-copy-docs-destination
          git add docs
          git commit -m "Copy docs from multiple repositories"

      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: add-updated-docs
          title: Copy docs from multiple repositories
          body: |
            This pull request copies the contents of the "docs" folder from source repositories that have updated contents in their `docs` folders.

          base: main
          draft: false
